language: ruby
rvm:
 - 2.6.3
services:
  - postgresql

# before_script:
#   - psql -c 'create database tarjimly_test;' -U postgres


env:
  global:
    - CC_TEST_REPORTER_ID=d6619829f91a85320403900a94a02139ea416a0b60150dd0f4603263b7028cc5

bundler_args:
    --without production


before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - bundle exec rake db:drop
  - bundle exec rake db:create
  - bundle exec rake db:migrate
  - bundle exec rspec
  - ./cc-test-reporter format-coverage --output coverage/codeclimate.$SUITE.json
  - bundle exec cucumber
  - ./cc-test-reporter format-coverage --output coverage/codeclimate.$SUITE.json

after_script:
  - ./cc-test-reporter sum-coverage coverage/codeclimate.*.json | ./cc-test-reporter upload-coverage
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

