language: ruby
rvm:
 - 2.6.3

services:
  - postgresql
before_script:
  - psql -c 'create database tarjimly_test;' -U postgres

  # before_script:
  # - cp config/database.yml.travis config/database.yml