development:
  adapter: postgresql
  encoding: unicode
  database: tarjimly_development
  pool: 5
  password:
  timeout: 5000
 
test:
  adapter: postgresql
  encoding: unicode
  database: tarjimly_test
  pool: 5
  password:
  timeout: 5000